#!/usr/bin/env python3
"""Engine-level gates for the `jackal.programming.source` domain pack.

Every case here drives the pinned Anubis engine as a subprocess and, where the
engine emits a certificate, the real independent checker
(`tools/test_exists_verify.py`) as a second subprocess. Nothing is stubbed and
no expected value is written by hand: declaration line numbers and counts are
derived by calling the checker's own `find_declarations`, and every refusal
class is read out of the process output.

Case data comes from the frozen corpus at `tests/corpus/programming_corpus_v1.json`
so that the expectations are observations of a recorded run rather than
assertions invented here. The corpus is regenerated by
`tests/corpus/generate_pack_corpus.py --freeze` and audited by `--self-check`.

The boundary these gates defend
-------------------------------
`test-exists` is byte-exact about a structural fact, so its assurance ceiling is
`exact` -- and a test existing is never evidence that the code under test is
correct, so its consequence ceiling stops at `informational`. The engine
validates only canonical *form*; every claim about the bytes on disk is
established by the checker or not at all. The `poison` cases below are the
interesting half: each one is a well-formed certificate the engine happily mints
and the checker refuses.

What these gates do NOT establish
---------------------------------
That a symbol the checker finds is a test, that it runs, that it asserts
anything, or that it covers whatever a surrounding document claims. Those are
permanent nonclaims of the pack, not gaps in this file.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _load_generator():
    path = ROOT / "tests" / "corpus" / "generate_pack_corpus.py"
    spec = importlib.util.spec_from_file_location("jackal_pack_corpus", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


GEN = _load_generator()

PY_FIXTURE = GEN.PY_FIXTURE
DOCSTRING_FIXTURE = GEN.DOCSTRING_FIXTURE
RAW_STRING_FIXTURE = GEN.RAW_STRING_FIXTURE
LINE_COMMENT_FIXTURE = GEN.LINE_COMMENT_FIXTURE
BLOCK_COMMENT_FIXTURE = GEN.BLOCK_COMMENT_FIXTURE
CLAIM_DOC = GEN.CLAIM_DOC


class ProgrammingPackCase(unittest.TestCase):
    """Shared harness: one engine build for the whole module, plus replay."""

    CORPUS = "programming"

    @classmethod
    def setUpClass(cls) -> None:
        if not GEN.ANUBIS.is_file():
            raise unittest.SkipTest(f"pinned Anubis compiler unavailable at {GEN.ANUBIS}")
        cls.engine = GEN.Engine.shared()
        cls.corpus = GEN.load_corpus(cls.CORPUS)
        cls.rows = GEN.cases_by_id(cls.corpus)

    def row(self, case_id: str) -> dict:
        self.assertIn(case_id, self.rows, f"{case_id} is not in the frozen corpus")
        return self.rows[case_id]

    def replay(self, case_id: str):
        """Re-run one frozen case live and assert it still behaves identically.

        Returns `(observation, verdict)`; `verdict` is None for engine refusals,
        which emit no certificate to check.
        """
        row = self.row(case_id)
        argv = list(row["argv"])
        if row["invocation"] == "pack-route":
            observed = self.engine.route(
                row.get("route_pack_id", self.corpus["pack_id"]),
                row.get("route_operation_id", row["operation_id"]),
                *argv,
            )
        else:
            observed = self.engine.run(row["engine_command"], *argv)

        self.assertEqual(observed.returncode, row["engine"]["returncode"])
        self.assertEqual(observed.refusal_class, row["engine"]["refusal_class"])
        self.assertEqual(observed.stdout, row["engine"]["stdout"])

        if row["checker"] is None:
            return observed, None

        certificate = observed.certificate(GEN.TEST_EXISTS_PREFIX)
        if "tamper" in row:
            certificate = GEN.apply_tamper(certificate, GEN.TEST_EXISTS_PREFIX, row["tamper"])
        self.assertEqual(certificate, row["certificate"])
        verdict = GEN.check_test_exists(certificate)
        self.assertEqual(verdict.summary, row["checker"]["verdict"], verdict.line)
        self.assertEqual(verdict.returncode, row["checker"]["returncode"])
        return observed, verdict

    def assertEngineRefusal(self, case_id: str, expected: str) -> None:
        observed, verdict = self.replay(case_id)
        self.assertNotEqual(observed.returncode, 0)
        self.assertEqual(observed.refusal_class, expected)
        self.assertIsNone(verdict)
        # No certificate may leak out of a refusal, or a caller could scrape a
        # partial line out of the transcript and check it in isolation.
        self.assertNotIn(GEN.TEST_EXISTS_PREFIX, observed.stdout)

    def assertCheckerRefusal(self, case_id: str, expected: str) -> None:
        observed, verdict = self.replay(case_id)
        self.assertEqual(observed.returncode, 0, "the engine must mint this certificate")
        self.assertIsNotNone(verdict)
        assert verdict is not None
        self.assertEqual(verdict.reason_class, expected, verdict.line)
        self.assertEqual(verdict.returncode, 2)


class ProgrammingHarnessTest(ProgrammingPackCase):
    """Validate the instrument before trusting any number it produces."""

    def test_harness_drives_the_pinned_compiler(self) -> None:
        self.assertEqual(self.engine.anubis_pin, GEN.ANUBIS.name)
        self.assertEqual(
            self.engine.engine_source_sha256,
            hashlib.sha256((ROOT / "jackal_calc.anb").read_bytes()).hexdigest(),
        )
        self.assertIn(self.engine.mode, ("prebuilt-native", "launcher-per-call"))
        self.assertIn("exact-cert=", self.engine.probe_stdout)

    def test_fast_path_is_byte_identical_to_the_jackal_launcher(self) -> None:
        """The whole suite rests on this: the fast path is the same engine.

        `Engine.__init__` already proves it for the build probe. This repeats the
        proof for a `test-exists` invocation through the real `./jackal` script,
        which recompiles from `jackal_calc.anb` via `anubis run`, so the parity
        claim is not confined to one command.
        """
        if self.engine.mode != "prebuilt-native":
            self.skipTest("harness is already using the launcher for every call")
        argv = list(self.row("positive_test_exists_single_declaration")["argv"])
        fast = self.engine.run("test-exists", *argv)
        launched = self.engine.run_via_launcher("test-exists", *argv)
        self.assertEqual(launched.returncode, 0, launched.stderr[-800:])
        self.assertEqual(launched.stdout, fast.stdout)

    def test_corpus_fixture_digests_still_match_disk(self) -> None:
        for entry in self.corpus["fixtures"]:
            with self.subTest(fixture=entry["path"]):
                self.assertEqual(GEN.sha256_file(entry["path"]), entry["sha256"])

    def test_corpus_checker_identity_still_matches_disk(self) -> None:
        self.assertEqual(
            GEN.sha256_file(self.corpus["checker"]["path"]),
            self.corpus["checker"]["sha256"],
        )

    def test_corpus_aggregate_digest_is_self_consistent(self) -> None:
        recomputed = GEN.corpus_digest(self.corpus)
        self.assertEqual(self.corpus[GEN.DIGEST_KEY], recomputed)

    def test_corpus_covers_all_three_case_classes(self) -> None:
        counts = self.corpus["case_counts"]
        self.assertGreaterEqual(counts["positive"], 6)
        self.assertGreaterEqual(counts["refusal"], 9)
        self.assertGreaterEqual(counts["poison"], 8)


class ProgrammingPositiveTest(ProgrammingPackCase):
    def test_positive_test_exists_single_declaration_is_accepted(self) -> None:
        observed, verdict = self.replay("positive_test_exists_single_declaration")
        self.assertIn("status=structural-exact", observed.stdout)
        self.assertIn("consequence=informational", observed.stdout)
        assert verdict is not None
        self.assertEqual(verdict.summary, "ACCEPT")
        # The line and count in the certificate are the checker's own answer,
        # never a hand-written number.
        argv = self.row("positive_test_exists_single_declaration")["argv"]
        self.assertEqual(argv[3], GEN.declaration_line(PY_FIXTURE, "corpus_python_target"))
        self.assertEqual(argv[4], GEN.declaration_count(PY_FIXTURE, "corpus_python_target"))

    def test_positive_test_exists_two_declarations_first_line_is_accepted(self) -> None:
        _, verdict = self.replay("positive_test_exists_two_declarations_first_line")
        assert verdict is not None
        self.assertEqual(verdict.summary, "ACCEPT")
        self.assertEqual(GEN.declaration_count(PY_FIXTURE, "corpus_python_twice"), "2")

    def test_positive_test_exists_two_declarations_second_line_is_accepted(self) -> None:
        _, verdict = self.replay("positive_test_exists_two_declarations_second_line")
        assert verdict is not None
        self.assertEqual(verdict.summary, "ACCEPT")

    def test_positive_test_exists_class_declaration_is_accepted(self) -> None:
        _, verdict = self.replay("positive_test_exists_class_declaration")
        assert verdict is not None
        self.assertEqual(verdict.summary, "ACCEPT")

    def test_positive_claim_cites_test_citation_resolves(self) -> None:
        observed, verdict = self.replay("positive_claim_cites_test_citation_resolves")
        self.assertIn("cited_symbol=corpus_python_target", observed.stdout)
        self.assertIn("consequence=informational", observed.stdout)
        assert verdict is not None
        self.assertEqual(verdict.summary, "ACCEPT")
        # The nonclaim must travel with the accept. Resolving a citation is not
        # validating one, and both the engine note and the checker say so.
        self.assertIn("citation-resolves-it-does-not-establish", observed.stdout)
        self.assertIn("whether the cited test covers the claim is NOT established", verdict.stdout)

    def test_control_checker_accepts_a_genuine_declaration_in_every_poison_fixture(self) -> None:
        """Non-vacuity control for the whole poison column.

        Each poison fixture also holds one real declaration. If the checker
        refused those too, every `cert-symbol-absent` below would be explained by
        a checker that cannot see declarations in that file at all, and the
        poison cases would prove nothing.
        """
        for case_id, fixture, symbol in (
            (
                "positive_test_exists_docstring_fixture_anchor",
                DOCSTRING_FIXTURE,
                "corpus_docstring_anchor",
            ),
            (
                "positive_test_exists_rust_raw_string_fixture_anchor",
                RAW_STRING_FIXTURE,
                "corpus_rust_raw_anchor",
            ),
            (
                "positive_test_exists_rust_comment_fixture_anchor",
                LINE_COMMENT_FIXTURE,
                "corpus_rust_comment_anchor",
            ),
            (
                "positive_test_exists_rust_block_comment_fixture_anchor",
                BLOCK_COMMENT_FIXTURE,
                "corpus_rust_block_anchor",
            ),
        ):
            with self.subTest(fixture=fixture):
                _, verdict = self.replay(case_id)
                assert verdict is not None
                self.assertEqual(verdict.summary, "ACCEPT")
                self.assertNotEqual(GEN.declarations(fixture, symbol), [])


class ProgrammingRouteParityTest(ProgrammingPackCase):
    """A pack route must preserve the direct command's stdout bytes exactly."""

    def _assert_parity(self, case_id: str, operation_id: str) -> None:
        row = self.row(case_id)
        argv = list(row["argv"])
        direct = self.engine.run(row["engine_command"], *argv)
        routed = self.engine.route(self.corpus["pack_id"], operation_id, *argv)
        self.assertEqual(direct.returncode, 0, direct.stderr[-800:])
        self.assertEqual(routed.returncode, 0, routed.stderr[-800:])
        self.assertEqual(routed.stdout, direct.stdout)
        # Byte parity would also hold if both sides emitted nothing, so pin the
        # payload the parity is about.
        self.assertIn(GEN.TEST_EXISTS_PREFIX, routed.stdout)
        self.assertTrue(row["route_parity"])

    def test_route_parity_test_exists(self) -> None:
        self._assert_parity(
            "positive_test_exists_single_declaration", GEN.OP_TEST_EXISTS
        )

    def test_route_parity_claim_cites_test(self) -> None:
        self._assert_parity(
            "positive_claim_cites_test_citation_resolves", GEN.OP_CLAIM_CITES
        )

    def test_route_parity_holds_for_every_certificate_bearing_case(self) -> None:
        for case_id, row in sorted(self.rows.items()):
            if row["checker"] is None:
                continue
            with self.subTest(case=case_id):
                self.assertIs(row["route_parity"], True)


class ProgrammingEngineRefusalTest(ProgrammingPackCase):
    """Form-level refusals. The engine emits no certificate for any of these."""

    def test_refusal_file_sha256_not_64_hex(self) -> None:
        self.assertEngineRefusal("refusal_file_sha256_not_64_hex", "prog-hex64")

    def test_refusal_absolute_file_path(self) -> None:
        self.assertEngineRefusal("refusal_absolute_file_path", "prog-path")

    def test_refusal_parent_traversal_file_path(self) -> None:
        self.assertEngineRefusal("refusal_parent_traversal_file_path", "prog-path")

    def test_refusal_symbol_not_an_identifier(self) -> None:
        self.assertEngineRefusal("refusal_symbol_not_an_identifier", "prog-symbol")

    def test_refusal_declaration_line_zero(self) -> None:
        self.assertEngineRefusal("refusal_declaration_line_zero", "prog-uint")

    def test_refusal_declaration_count_zero_is_an_absence(self) -> None:
        # Not `prog-uint`: zero is a well-formed integer, and the engine names
        # the real problem, which is that an absence is being offered as a fact.
        self.assertEngineRefusal(
            "refusal_declaration_count_zero_is_an_absence", "prog-absent"
        )

    def test_refusal_route_arity(self) -> None:
        self.assertEngineRefusal("refusal_route_arity_test_exists", "pack-request-arity")

    def test_refusal_unknown_pack_id(self) -> None:
        self.assertEngineRefusal("refusal_unknown_pack_id", "pack-id-unknown")

    def test_refusal_unknown_operation_id_does_not_fall_back(self) -> None:
        observed, _ = self.replay("refusal_unknown_operation_id")
        self.assertEqual(observed.refusal_class, "pack-operation-unknown")
        self.assertIn("no fallback is permitted", observed.refusal_detail or "")

    def test_refusal_empty_claim_text(self) -> None:
        self.assertEngineRefusal("refusal_empty_claim_text", "prog-text")

    def test_refusal_claim_text_over_2048_bytes(self) -> None:
        self.assertEngineRefusal("refusal_claim_text_over_2048_bytes", "prog-text")

    def test_refusal_direct_arity_names_no_pack_class(self) -> None:
        """Honest boundary: `pack-request-arity` belongs to the route, not the
        direct command.

        The direct command refuses a short argument list with a generic panic
        that names no refusal class. Asserting `pack-request-arity` here would
        have been a green test for a class the direct path never emits.
        """
        argv = list(self.row("positive_test_exists_single_declaration")["argv"])[:4]
        observed = self.engine.run("test-exists", *argv)
        self.assertNotEqual(observed.returncode, 0)
        self.assertIsNone(observed.refusal_class)
        self.assertIn("wrong number of arguments", observed.stderr)


class ProgrammingCheckerRefusalTest(ProgrammingPackCase):
    """Substance-level refusals: the engine mints, the checker refuses."""

    def test_poison_stale_content_hash(self) -> None:
        self.assertCheckerRefusal("poison_stale_content_hash", "cert-content-hash-mismatch")

    def test_poison_declaration_line_wrong(self) -> None:
        self.assertCheckerRefusal(
            "poison_declaration_line_wrong", "cert-declaration-line-mismatch"
        )

    def test_poison_declaration_count_inflated(self) -> None:
        self.assertCheckerRefusal(
            "poison_declaration_count_inflated", "cert-declaration-count-mismatch"
        )

    def test_poison_symbol_absent_entirely(self) -> None:
        self.assertCheckerRefusal("poison_symbol_absent_entirely", "cert-symbol-absent")

    def test_poison_declaration_only_in_python_docstring(self) -> None:
        self.assertCheckerRefusal(
            "poison_declaration_only_in_python_docstring", "cert-symbol-absent"
        )
        self.assertEqual(
            GEN.declarations(DOCSTRING_FIXTURE, "corpus_docstring_phantom"), []
        )

    def test_poison_declaration_only_in_rust_raw_string(self) -> None:
        self.assertCheckerRefusal(
            "poison_declaration_only_in_rust_raw_string", "cert-symbol-absent"
        )
        self.assertEqual(
            GEN.declarations(RAW_STRING_FIXTURE, "corpus_raw_string_phantom"), []
        )

    def test_poison_declaration_only_in_line_comment(self) -> None:
        self.assertCheckerRefusal(
            "poison_declaration_only_in_line_comment", "cert-symbol-absent"
        )
        self.assertEqual(
            GEN.declarations(LINE_COMMENT_FIXTURE, "corpus_line_comment_phantom"), []
        )

    def test_poison_declaration_only_in_block_comment(self) -> None:
        self.assertCheckerRefusal(
            "poison_declaration_only_in_block_comment", "cert-symbol-absent"
        )
        self.assertEqual(
            GEN.declarations(BLOCK_COMMENT_FIXTURE, "corpus_block_comment_phantom"), []
        )

    def test_poison_claim_text_not_in_document(self) -> None:
        self.assertCheckerRefusal(
            "poison_claim_text_not_in_document", "cert-claim-text-absent"
        )

    def test_poison_citation_dangles(self) -> None:
        self.assertCheckerRefusal("poison_citation_dangles", "cert-citation-dangling")
        # The document sentence is genuinely present; only the cited symbol is
        # missing. That is the exact defect this pack exists to catch: a claim
        # grounded in a real file that is still false.
        doc_text = (ROOT / CLAIM_DOC).read_text(encoding="utf-8")
        self.assertIn(GEN.CLAIM_DANGLES, doc_text)
        self.assertEqual(GEN.declarations(PY_FIXTURE, "corpus_absent_from_fixture"), [])


class ProgrammingBlankingIsLoadBearingTest(ProgrammingPackCase):
    """Attribute each poison refusal to the guard that actually causes it.

    "The checker refuses this" is not the same claim as "this specific guard
    refuses this". These tests disable one guard at a time on a private import of
    the checker -- the file on disk is never touched -- and record which phantoms
    become visible. Anything that stays invisible is refused by something else,
    and that is said rather than glossed.
    """

    def _unguarded_checker(self, *, blanking: bool, python_ast: bool):
        checker = GEN._load_module("probe_test_exists_verify", GEN.TEST_EXISTS_CHECKER)
        if not blanking:
            checker._blank_noncode = lambda text: text
        if not python_ast:
            checker._python_declarations = lambda text, symbol: None
        return checker

    def test_instrument_comment_and_string_blanking_is_load_bearing(self) -> None:
        # With the blanking pass disabled (and, for Python, the exact `ast` path
        # disabled too), these phantoms ARE found -- so the refusals recorded for
        # them are caused by those guards and not by an unrelated accident.
        probe = self._unguarded_checker(blanking=False, python_ast=False)
        for fixture, symbol in (
            (DOCSTRING_FIXTURE, "corpus_docstring_phantom"),
            (RAW_STRING_FIXTURE, "corpus_raw_string_phantom"),
            (BLOCK_COMMENT_FIXTURE, "corpus_block_comment_phantom"),
        ):
            with self.subTest(fixture=fixture):
                text = (ROOT / fixture).read_text(encoding="utf-8")
                unguarded = probe.find_declarations(
                    text, symbol, suffix=Path(fixture).suffix
                )
                self.assertNotEqual(
                    unguarded, [], "the fixture is not a trap for this guard at all"
                )
                self.assertEqual(GEN.declarations(fixture, symbol), [])

    def test_instrument_line_comment_phantom_is_refused_by_the_line_anchor(self) -> None:
        """Honest attribution: this one is NOT the blanking pass.

        A `// pub fn ...` line still starts with `//` after blanking is disabled,
        and every declaration pattern is anchored with `^\\s*`, so the pattern
        never matches. Claiming the blanking pass catches it would have been an
        overstatement, and the probe above is what showed the difference.
        """
        probe = self._unguarded_checker(blanking=False, python_ast=True)
        text = (ROOT / LINE_COMMENT_FIXTURE).read_text(encoding="utf-8")
        self.assertEqual(
            probe.find_declarations(text, "corpus_line_comment_phantom", suffix=".rs"), []
        )
        self.assertEqual(
            GEN.declarations(LINE_COMMENT_FIXTURE, "corpus_line_comment_phantom"), []
        )

    def test_instrument_python_ast_path_supersedes_the_regex_path(self) -> None:
        # The docstring phantom is refused twice over: the `ast` path never sees
        # it, and the blanking pass would remove it anyway. Disabling only `ast`
        # must still refuse, which is what defence in depth means here.
        probe = self._unguarded_checker(blanking=True, python_ast=False)
        text = (ROOT / DOCSTRING_FIXTURE).read_text(encoding="utf-8")
        self.assertEqual(
            probe.find_declarations(text, "corpus_docstring_phantom", suffix=".py"), []
        )
        # Control: the same unguarded checker still finds the real declaration.
        self.assertNotEqual(
            probe.find_declarations(text, "corpus_docstring_anchor", suffix=".py"), []
        )


class ProgrammingSymlinkRefusalTest(ProgrammingPackCase):
    """Path-safety refusals, which need a tree the repository must not contain.

    Symlinks are built in a temporary root and the checker is pointed at it with
    `--root`. The engine still mints the certificate -- it never reads the file --
    so these cases exercise the checker's own path guards.
    """

    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory(prefix="jackal-programming-symlink-")
        self.root = Path(self.temp.name)
        self.real = self.root / "genuine.py"
        self.real.write_text(
            "def symlink_probe_target(value):\n    return value\n", encoding="utf-8"
        )
        self.addCleanup(self.temp.cleanup)

    def _mint(self, file_path: str, sha: str, symbol: str, line: str, count: str):
        observed = self.engine.run("test-exists", file_path, sha, symbol, line, count)
        self.assertEqual(observed.returncode, 0, observed.stderr[-800:])
        return observed.certificate(GEN.TEST_EXISTS_PREFIX)

    def _sha(self, path: Path) -> str:
        return hashlib.sha256(path.read_bytes()).hexdigest()

    def test_control_temporary_root_accepts_the_real_file(self) -> None:
        # Non-vacuity control for this class: with no symlink in the way the very
        # same temp root and the very same checker ACCEPT.
        certificate = self._mint(
            "genuine.py", self._sha(self.real), "symlink_probe_target", "1", "1"
        )
        verdict = GEN.check_test_exists(certificate, root=self.root)
        self.assertEqual(verdict.summary, "ACCEPT", verdict.line)

    def test_poison_file_path_names_a_symlink(self) -> None:
        (self.root / "linked.py").symlink_to(self.real)
        certificate = self._mint(
            "linked.py", self._sha(self.real), "symlink_probe_target", "1", "1"
        )
        verdict = GEN.check_test_exists(certificate, root=self.root)
        self.assertEqual(verdict.reason_class, "cert-path-symlink", verdict.line)
        self.assertEqual(verdict.returncode, 2)

    def test_poison_symlinked_directory_on_the_path(self) -> None:
        real_dir = self.root / "real_pkg"
        real_dir.mkdir()
        target = real_dir / "genuine.py"
        target.write_text(
            "def symlink_probe_target(value):\n    return value\n", encoding="utf-8"
        )
        (self.root / "linked_pkg").symlink_to(real_dir, target_is_directory=True)
        certificate = self._mint(
            "linked_pkg/genuine.py", self._sha(target), "symlink_probe_target", "1", "1"
        )
        verdict = GEN.check_test_exists(certificate, root=self.root)
        self.assertEqual(verdict.reason_class, "cert-path-symlink", verdict.line)
        self.assertIn("linked_pkg", verdict.line)


class ProgrammingHandBuiltCertificateTest(ProgrammingPackCase):
    """Checker guards that the engine's own form checks make unreachable.

    These certificates cannot be produced by the pinned engine, so they are built
    directly. That is stated rather than hidden: the point is that the checker
    does not rely on the engine having already refused.
    """

    def _check(self, claim: dict, kind: str = "test-exists"):
        envelope = {
            "claim": claim,
            "kind": kind,
            "schema": "jackal-test-exists-cert-v1",
            "witness": {},
        }
        payload = GEN.TEST_EXISTS_PREFIX + json.dumps(
            envelope, sort_keys=True, separators=(",", ":")
        )
        return GEN.check_test_exists(payload)

    def test_hand_built_zero_count_certificate_is_an_absence(self) -> None:
        verdict = self._check(
            {
                "declaration_count": "0",
                "declaration_line": "1",
                "file_path": PY_FIXTURE,
                "file_sha256": GEN.sha256_file(PY_FIXTURE),
                "symbol": "corpus_python_target",
            }
        )
        self.assertEqual(verdict.reason_class, "cert-absence-as-existence", verdict.line)

    def test_hand_built_absolute_path_certificate_is_unsafe(self) -> None:
        verdict = self._check(
            {
                "declaration_count": "1",
                "declaration_line": "1",
                "file_path": "/etc/passwd",
                "file_sha256": "0" * 64,
                "symbol": "root",
            }
        )
        self.assertEqual(verdict.reason_class, "cert-path-unsafe", verdict.line)

    def test_hand_built_control_certificate_is_still_accepted(self) -> None:
        # Non-vacuity control: the hand-built envelope shape itself is fine, so
        # the two refusals above are attributable to their claims.
        verdict = self._check(
            {
                "declaration_count": GEN.declaration_count(PY_FIXTURE, "corpus_python_target"),
                "declaration_line": GEN.declaration_line(PY_FIXTURE, "corpus_python_target"),
                "file_path": PY_FIXTURE,
                "file_sha256": GEN.sha256_file(PY_FIXTURE),
                "symbol": "corpus_python_target",
            }
        )
        self.assertEqual(verdict.summary, "ACCEPT", verdict.line)


class ProgrammingCorpusReplayTest(ProgrammingPackCase):
    """Replay every frozen case, including any not named individually above."""

    def test_every_frozen_case_replays_identically(self) -> None:
        for case_id in sorted(self.rows):
            with self.subTest(case=case_id):
                self.replay(case_id)

    def test_every_frozen_case_is_named_by_an_individual_test(self) -> None:
        """Guard against a corpus row that only the bulk replay ever touches.

        A case reachable solely through the loop above is easy to lose track of;
        requiring each `case_id` to appear in some test method's source keeps the
        individual gates and the corpus in step.
        """
        source = Path(__file__).read_text(encoding="utf-8")
        unnamed = [
            case_id
            for case_id in sorted(self.rows)
            if f'"{case_id}"' not in source
        ]
        self.assertEqual(unnamed, [])


class ProgrammingCaseCensusTest(ProgrammingPackCase):
    def test_case_census(self) -> None:
        positive = [n for n in dir(ProgrammingPositiveTest) if n.startswith("test_positive_")]
        refusal = [n for n in dir(ProgrammingEngineRefusalTest) if n.startswith("test_refusal_")]
        poison = [
            n for n in dir(ProgrammingCheckerRefusalTest) if n.startswith("test_poison_")
        ] + [n for n in dir(ProgrammingSymlinkRefusalTest) if n.startswith("test_poison_")]
        control = [
            n
            for n in dir(ProgrammingPositiveTest)
            + dir(ProgrammingSymlinkRefusalTest)
            + dir(ProgrammingHandBuiltCertificateTest)
            if n.startswith("test_control_") or "control" in n
        ]
        instrument = [
            n for n in dir(ProgrammingBlankingIsLoadBearingTest) if n.startswith("test_instrument_")
        ] + [n for n in dir(ProgrammingHarnessTest) if n.startswith("test_")]
        print(
            f"\nprogramming_case_census positive={len(positive)} "
            f"engine_refusal={len(refusal)} checker_refusal={len(poison)} "
            f"control={len(control)} instrument={len(instrument)} "
            f"corpus_cases={len(self.rows)} "
            f"corpus_counts={self.corpus['case_counts']}",
            file=sys.stderr,
        )
        self.assertGreaterEqual(len(positive), 5)
        self.assertGreaterEqual(len(refusal), 9)
        self.assertGreaterEqual(len(poison), 12)
        self.assertGreaterEqual(len(control), 3)
        self.assertGreaterEqual(len(instrument), 8)


if __name__ == "__main__":
    unittest.main(verbosity=2)
